### ISSUE TITLE
Support traits

### ISSUE THREAD

**Issue by goatherd** [packfire-archived/pdc#12]
For traits two issues remain:
- "File and class name mismatch" within the defining file
- "Unused" when using traits within a class definition

I would be able to provide the code in February if needed, but wanted to note down the issue sooner.

**Comment by goatherd** [comment]
Example

``` php
// MyTrait.php
namespace MyTest;

trait MyTrait {}
```

``` php
// MyClass.php
namespace MyTest;

use MyTest\MyTrait;

class MyClass {
    use MyTrait;
}
```

**Comment by mauris** [comment]
@goatherd thank you so much for bringing up traits. 

I must admit that I haven't been using traits at all. I will update PDC and release Traits support soon. 

thank you!

**Comment by mauris** [comment]
I am left with the other issue regarding traits: the unused problem.

the use statement is generally used by namespace usage and coding for this is a little difficult because PDC needs to differentiate namespace `use` and traits `use`. 

traits `use` can be like:

``` php
<?php
use Test\MyTrait1;
use Test\MyTrait2;

class MyClass{
    use MyTrait1, MyTrait2;

}
```

**Comment by goatherd** [comment]
I'm not sure whether you like the idea, but there is a tool for tokenised php code testing called [PHP CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer).

Maybe it would help to rewrite your tests as 'standard' (plug-in) for codesniffer.
That way you only need to consider the testing part and no longer care about tokenising nor parsing.

Not using the tokenizer but regular expression for such things is guaranteed to give you quirks. With changes to new PHP versions those will increase with time as well and you need to cover bad practice (as `use MyTrait1, MyTrait2;` within a class).

But if you want to stick to the way it works: look for nesting here. A `use` that occurs within brackets is semantically different from a `use` that does not. The first would _consume_ while the second _provides_ you might say.
The expression would be slow since it must test recursive the number of opened and closed brackets.

**Comment by mauris** [comment]
@goatherd I have updated PDC to complete the features as requested in this issue. I will be closing this issue as I tag a new stable release. Thank you so much for your input. (:

Upcoming release: v 1.0.8

**Comment by goatherd** [comment]
Sorry, been unexpected busy for some time!

I did test against 1.0.8, 1.0.10 and develop, but either report errors (not found/ unused). Working on a patch now.

**Comment by goatherd** [comment]
See #20 for unit tests/ examples.

**Comment by mauris** [comment]
On my side 1.0.10 seemed to be able to detect traits properly. What were the exact misdetections that PDC made for your end?
