### ISSUE TITLE
psr-2

### ISSUE THREAD

**Issue by goatherd** [packfire-archived/pdc#21]
It would help to work on patches if the source code would be closer to psr-2.

Especially hard for me to scan are:
- missing spaces around keywords: `if(` instead of `if (` or `}else{` instead of `} else {`
- method/ function/ class braces not being on the next line
- closing `);` or `) {` is not on a single line for multi-line function calls
- no linefeed at the end of class files

What do you think of those?
A patch would be trivial to supply.

**Comment by mauris** [comment]
Hey @goatherd, do you mean that the scanned source code needs to be closer to PSR-2?

**Comment by goatherd** [comment]
Not the scanned source code. Your pdc code was what I meant.
I have rather bad eye sight and find it much more simple to scan/ read psr-2 formated code. As almost all major frameworks opted for psr-2 I was just curious what you thought about it.

**Comment by mauris** [comment]
I see what I can do on my end after merging all the existing patches?

**Comment by mauris** [comment]
A patch for PSR-2 compliance has been implemented in the last push. 

See commit c440ea729a853b8c41c2720d628c40fb1dec282d
